name: primeira-pipeline
on: 
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs:
  primeiro_job:
    name: "Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Primeira ação"
        run: echo "hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Primeiro workflow criado"
          echo "Parabéns!"
      - name: "Script python"
        run: |
          variavel = "Hello World!!!"
          print(variavel)
        shell: python
  segundo_job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificar a versão atual do Node JS"
        run: node --version
      - name: "Definição da versao 24.14.0 LTS do Node JS"
        run: node --version
      - uses: actions/setup-node@v6
        with:
          node-version: "24.10.0"
      - name: "Verificar a versão atual do Node JS depois de instalar"
        run: node --version
